### Create a new coupon

POST {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/coupon/create

Content-Type: application/json
Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}

{
    "code": "DEYVIN_20",
    "discountKind": "PERCENTAGE",
    "discount": 123,
    "notes": "Cupom de desconto pro meu público",
    "maxRedeems": -1,
    "metadata": {}
}

### List all coupons

GET {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/coupon/list

Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}
