### Get the MRR data

GET {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/public-mrr/mrr

Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}

### Get merchant info

GET {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/public-mrr/merchant-info

Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}

### Get revenue by period

@START_DATE = 2026-01-01
@END_DATE = 2026-01-31

GET {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/public-mrr/revenue?startDate={{START_DATE}}&endDate={{END_DATE}}

Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}