### Get the MRR data

GET {{BASE_URL}}/{{API_VERSION}}/public-mrr/mrr

Authorization: Bearer {{ABACATEPAY_API_KEY}}

### Get merchant info

GET {{BASE_URL}}/{{API_VERSION}}/public-mrr/merchant-info

Authorization: Bearer {{ABACATEPAY_API_KEY}}

### Get revenue by period

@START_DATE = 2026-01-01
@END_DATE = 2026-01-31

GET {{BASE_URL}}/{{API_VERSION}}/public-mrr/revenue?startDate={{START_DATE}}&endDate={{END_DATE}}

Authorization: Bearer {{ABACATEPAY_API_KEY}}
