### Create a new withdraw

POST {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/withdraw/create

Content-Type: application/json
Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}

{
    "externalId": "withdraw-1234",
    "method": "PIX",
    "amount": 5000,
    "pix": {
        "type": "CPF",
        "key": "123.456.789-01"
    },
    "description": "Saque para conta principal"
}

### Get withdraw details

@WITHDRAW_ID = withdraw-1234

GET {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/withdraw/get?externalId={{WITHDRAW_ID}}

Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}

### List all withdraws

GET {{$dotenv .env BASE_URL}}/{{$dotenv .env API_VERSION}}/withdraw/list

Authorization: Bearer {{$dotenv .env ABACATEPAY_API_KEY}}
